AWSTemplateFormatVersion: '2010-09-09'
Description: SQS stack

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: medisplain

Resources:
  FileUploadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AWS::StackName, "file-upload", !Ref Environment ] ]
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileUploadDeadLetterQueue.Arn
        maxReceiveCount: 1  # Move to DLQ after 1 failed receive (i.e., Lambda error)

  FileUploadDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AWS::StackName, "file-upload-dlq", !Ref Environment ] ]
      MessageRetentionPeriod: 1209600  # 14 days

  FileToAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AWS::StackName, "file-to-analyze", !Ref Environment ] ]
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileToAnalyzeDeadLetterQueue.Arn
        maxReceiveCount: 1

  FileToAnalyzeDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AWS::StackName, "file-to-analyze-dlq", !Ref Environment ] ]
      MessageRetentionPeriod: 1209600

Outputs:
  FileUploadQueueRef:
    Value: !Ref FileUploadQueue
    Export:
      Name: !Sub FileUploadQueueRef${Environment}
  FileUploadQueueArn:
    Value: !GetAtt FileUploadQueue.Arn
    Export:
      Name: !Sub FileUploadQueueArn${Environment}
  FileToAnalyzeQueueRef:
    Value: !Ref FileToAnalyzeQueue
    Export:
      Name: !Sub FileToAnalyzeQueueRef${Environment}
  FileToAnalyzeQueueArn:
    Value: !GetAtt FileToAnalyzeQueue.Arn
    Export:
      Name: !Sub FileToAnalyzeQueueArn${Environment}
  FileUploadDeadLetterQueueRef:
    Value: !Ref FileUploadDeadLetterQueue
    Export:
      Name: !Sub FileUploadDeadLetterQueueRef${Environment}
  FileUploadDeadLetterQueueArn:
    Value: !GetAtt FileUploadDeadLetterQueue.Arn
    Export:
      Name: !Sub FileUploadDeadLetterQueueArn${Environment}
  FileToAnalyzeDeadLetterQueueRef:
    Value: !Ref FileToAnalyzeDeadLetterQueue
    Export:
      Name: !Sub FileToAnalyzeDeadLetterQueueRef${Environment}
  FileToAnalyzeDeadLetterQueueArn:
    Value: !GetAtt FileToAnalyzeDeadLetterQueue.Arn
    Export:
      Name: !Sub FileToAnalyzeDeadLetterQueueArn${Environment}