AWSTemplateFormatVersion: '2010-09-09'
Description: SQS stack

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: bagalyze

Resources:
  FileUploadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AWS::StackName, "file-upload", !Ref Environment ] ]
      VisibilityTimeout: 30

Outputs:
  FileUploadQueueRef:
    Value: !Ref FileUploadQueue
    Export:
      Name: FileUploadQueueRef

  FileUploadQueueArn:
    Value: !GetAtt FileUploadQueue.Arn
    Export:
      Name: FileUploadQueueArn