AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Lambda consumer, to DynamoDb

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: medisplain
  FunctionConsumeName:
    Type: String
    Default: consume-file-metadata.zip
  DynamoMetadataTableName:
    Type: String
    Default: user-file-metadata

Resources:
  FileMetadataConsumerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${Project}-lambda-s3-dynamo-access-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Project}-${DynamoMetadataTableName}-${Environment}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                Resource: !Sub
                  - "arn:aws:s3:::${BucketName}/*"
                  - BucketName:
                      Fn::ImportValue:
                        Fn::Sub: FileUploadBucket${Environment}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: FileUploadQueueArn${Environment}
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: FileUploadDeadLetterQueueArn${Environment}

  FileMetadataConsumerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-function-${Environment}"
      Handler: consume_file_metadata.handler
      Role: !GetAtt FileMetadataConsumerRole.Arn
      Runtime: python3.11
      Timeout: 15
      Code:
        S3Bucket:
          Fn::ImportValue:
            Fn::Sub: LambdaCodeBucket${Environment}
        S3Key: !Ref FunctionConsumeName
      Environment:
        Variables:
          TABLE_NAME: !Sub ${Project}-${DynamoMetadataTableName}-${Environment}
      # AWS bypasses the SQS RedrivePolicy when Lambda is the consumer and uses the DeadLetterConfig property instead.
      DeadLetterConfig:
        TargetArn:
          Fn::ImportValue:
            Fn::Sub: FileUploadDeadLetterQueueArn${Environment}

  FileUploadQueueEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn:
        Fn::ImportValue:
          Fn::Sub: FileUploadQueueArn${Environment}
      FunctionName: !Ref FileMetadataConsumerFunction
      Enabled: true