AWSTemplateFormatVersion: '2010-09-09'
Description: GET User metadata API resource, with Lambda handler

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: medisplain
  FunctionMetadataUserGet:
    Type: String
    Default: get-user-metadata.zip

Resources:
  GetUserMetadataFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref AWS::StackName, "function" ,!Ref Environment ] ]
      Handler: get_user_metadata.handler
      Role: !GetAtt LogAndDynamoAccessLambdaRole.Arn
      Runtime: python3.11
      Timeout: 10
      Code:
        S3Bucket:
          Fn::ImportValue:
            Fn::Sub: LambdaCodeBucket${Environment}
        S3Key: !Ref FunctionMetadataUserGet
      Environment:
        Variables:
          TABLE_NAME:
            Fn::ImportValue:
              Fn::Sub: UserFileMetadataTable${Environment}

  LogAndDynamoAccessLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${Project}-allow-dynamo-db-read-access-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: UserFileMetadataTableArn${Environment}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ApiGatewayUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Fn::ImportValue:
          Fn::Sub: ApiGatewayRestApi${Environment}
      ParentId:
        Fn::ImportValue:
          Fn::Sub: ApiGatewayRestApiRootResourceId${Environment}
      PathPart: user

  ApiGatewayGetUserMetadataMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ApiGatewayUserResource
      RestApiId:
        Fn::ImportValue:
          Fn::Sub: ApiGatewayRestApi${Environment}
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId:
        Fn::ImportValue:
          Fn::Sub: ApiAuthorizer${Environment}
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref AWS::Region
            LambdaArn: !GetAtt GetUserMetadataFunction.Arn
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true

  ApiGatewayGetUserOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId: !Ref ApiGatewayUserResource
      RestApiId:
        Fn::ImportValue:
          Fn::Sub: ApiGatewayRestApi${Environment}
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'http://localhost:4200'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true

  LambdaApiGetUserPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetUserMetadataFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/GET/user'
        - RestApiId:
            Fn::ImportValue:
              Fn::Sub: ApiGatewayRestApi${Environment}

Outputs:
  LogAndDynamoAccessLambdaRole:
    Value: !Ref LogAndDynamoAccessLambdaRole
    Export:
      Name: !Sub LogAndDynamoAccessLambdaRole${Environment}
  LogAndDynamoAccessLambdaRoleArn:
    Value: !GetAtt LogAndDynamoAccessLambdaRole.Arn
    Export:
      Name: !Sub LogAndDynamoAccessLambdaRoleArn${Environment}