AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront OAC and distro

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: medisplain
  KeyGroupId:
    Type: String

Resources:
  CloudFrontDownloadOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-download-access-control-${Environment}"
        Description: Access control for CloudFront to access S3
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDownloadDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: ''
        Origins:
          - Id: S3Origin
            DomainName: !Sub
              - "${UploadBucket}.s3.${AWS::Region}.amazonaws.com"
              - UploadBucket:
                  Fn::ImportValue:
                    Fn::Sub: FileUploadBucket${Environment}
            OriginAccessControlId: !Ref CloudFrontDownloadOAC
            S3OriginConfig: { }
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD ]
          CachedMethods: [ GET, HEAD ]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TrustedKeyGroups:
            - !Ref KeyGroupId
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100
        HttpVersion: http2


Outputs:
  CloudFrontDownloadDistributionDomainName:
    Value: !GetAtt CloudFrontDownloadDistribution.DomainName
    Export:
      Name: !Sub CloudFrontDownloadDistributionDomainName${Environment}
  CloudFrontDownloadDistribution:
    Value: !Ref CloudFrontDownloadDistribution
    Export:
      Name: !Sub CloudFrontDownloadDistribution${Environment}
  CloudFrontDownloadDistributionId:
    Value: !GetAtt CloudFrontDownloadDistribution.Id
    Export:
      Name: !Sub CloudFrontDownloadDistributionId${Environment}