AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Lambda consumer, to AI process, then DynamoDb

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
    Default: medisplain
  FunctionAIProcessConsumerName:
    Type: String
    Default: consume-file-ai-process.zip
  DynamoMetadataTableName:
    Type: String
    Default: user-file-metadata
  ParametersAndSecretsExtensionPort:
    Type: String
    Default: 2773
  SecretsManagerTTL:
    Type: String
    Default: 120

Resources:
  FileAIProcessConsumerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${Project}-lambda-s3-dynamo-access-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Project}-${DynamoMetadataTableName}-${Environment}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                Resource: !Sub
                  - "arn:aws:s3:::${BucketName}/*"
                  - BucketName:
                      Fn::ImportValue:
                        Fn::Sub: FileUploadBucket${Environment}
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub
                  - "arn:aws:s3:::${BucketName}"
                  - BucketName:
                      Fn::ImportValue:
                        Fn::Sub: FileUploadBucket${Environment}
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub
                  - "arn:aws:s3:::${BucketName}"
                  - BucketName:
                      Fn::ImportValue:
                        Fn::Sub: FileUploadBucket${Environment}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: FileToAnalyzeQueueArn${Environment}
              - Effect: Allow
                Action:
                  - sqs:sendMessage
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: FileToAnalyzeDeadLetterQueueArn${Environment}
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  Fn::ImportValue:
                    Fn::Sub: OpenAIApiKeySecretRef${Environment}
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - Fn::Sub:
                      - "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${OpenAISystemPromptName}"
                      - OpenAISystemPromptName: !ImportValue OpenAISystemPromptName  #shall be modified if OpenAISystemPromptName${Environment} is exported
                  - Fn::Sub:
                      - "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${OpenAIUserPromptName}"
                      - OpenAIUserPromptName: !ImportValue OpenAIUserPromptName #shall be modified if OpenAIUserPromptName${Environment}

  FileAIProcessConsumerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-function-${Environment}"
      Handler: consume_file_ai_process.handler
      Role: !GetAtt FileAIProcessConsumerRole.Arn
      Runtime: python3.11
      Timeout: 60
      Code:
        S3Bucket:
          Fn::ImportValue:
            Fn::Sub: LambdaCodeBucket${Environment}
        S3Key: !Ref FunctionAIProcessConsumerName
      Layers:
        - arn:aws:lambda:eu-central-1:187925254637:layer:AWS-Parameters-and-Secrets-Lambda-Extension:17
        - !Ref PyPDFLayer
        - !Ref OpenAILayer
      Environment:
        Variables:
          TABLE_NAME: !Sub ${Project}-${DynamoMetadataTableName}-${Environment}
          PARAMETERS_SECRETS_EXTENSION_HTTP_PORT: !Ref ParametersAndSecretsExtensionPort
          OPENAI_API_KEY_SECRET_ARN:
            Fn::ImportValue:
              Fn::Sub: OpenAIApiKeySecretRef${Environment}
          SECRETS_MANAGER_TTL: !Ref SecretsManagerTTL
          OPENAI_SYSTEM_PROMPT_PARAMETER_NAME: !ImportValue OpenAISystemPromptName #shall be modified if OpenAISystemPromptName${Environment}
          OPENAI_USER_PROMPT_PARAMETER_NAME: !ImportValue OpenAIUserPromptName #shall be modified if OpenAIUserPromptName${Environment}
      # AWS bypasses the SQS RedrivePolicy when Lambda is the consumer and uses the DeadLetterConfig property instead.
      DeadLetterConfig:
        TargetArn:
          Fn::ImportValue:
            Fn::Sub: FileToAnalyzeDeadLetterQueueArn${Environment}

  FileToAnalyzeQueueEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn:
        Fn::ImportValue:
          Fn::Sub: FileToAnalyzeQueueArn${Environment}
      FunctionName: !Ref FileAIProcessConsumerFunction
      Enabled: true

  PyPDFLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: pypdf
      Description: Layer with pypdf2 library that extract text from pdf file
      Content:
        S3Bucket:
          Fn::ImportValue:
            Fn::Sub: LambdaCodeBucket${Environment}
        S3Key: layers/pypdf-layer.zip
      CompatibleRuntimes:
        - python3.11
      LicenseInfo: "MIT"

  OpenAILayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: openai
      Description: Layer with openai library
      Content:
        S3Bucket:
          Fn::ImportValue:
            Fn::Sub: LambdaCodeBucket${Environment}
        S3Key: layers/openai-layer.zip
      CompatibleRuntimes:
        - python3.11
      LicenseInfo: "MIT"

Outputs:
  FileAIProcessConsumerFunction:
    Description: AI process Lambda
    Value: !Ref FileAIProcessConsumerFunction
    Export:
      Name: !Sub FileAIProcessConsumerFunction${Environment}