AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend hosting for medisplain.brighthills.cloud with CloudFront + S3

Parameters:
  Environment:
    Type: String
  DomainName:
    Type: String
    Default: medisplain.brighthills.cloud
  CertificateArn:
    Type: String
    Description: "ACM Certificate ARN for CloudFront"
    Default: arn:aws:acm:us-east-1:390844756520:certificate/e00e068e-c449-4fa6-8052-e20c81a65af4
  Route53ZoneId:
    Type: String
    Default: Z003209932MEVPLFYJGBR

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DomainName}/*"

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName

  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CloudFrontOAI
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: S3Origin
            DomainName: !ImportValue SiteBucketRegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2

  Route53AliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53ZoneId
      Name: !Ref DomainName  # medisplain.brighthills.cloud
      Type: A
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # global static value for all CloudFront distributions

  Route53Ipv6AliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53ZoneId
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !GetAtt SiteDistribution.DomainName